import liz from '@/assets/projects/rc-phone/users/liz@2x.png';
import type { UserCardProps } from '@/components/UserCard/_types';

export const userCards: UserCardProps[] = [
	{
		photo: liz,
		name: 'User Name',
		role: 'User Role',
		company: 'Company Name',
		quote: `What matters to me is that these screens are in the right spot. It's the number one way I use Ring (computer and phone) …`,
		videoLabel: "User's story",
		videoUrl: 'Test Url',
		height: 450,
		width: 300,
	},
	{
		photo: liz,
		name: 'User Name',
		role: 'User Role',
		company: 'Company Name',
		quote: `What matters to me is that these screens are in the right spot. It's the number one way I use Ring (computer and phone) …`,
		videoLabel: "User's story",
		videoUrl: 'Test Url',
		height: 450,
		width: 300,
	},
	{
		photo: liz,
		name: 'User Name',
		role: 'User Role',
		company: 'Company Name',
		quote: `What matters to me is that these screens are in the right spot. It's the number one way I use Ring (computer and phone) …`,
		videoLabel: "User's story",
		videoUrl: 'Test Url',
		height: 450,
		width: 300,
	},
	{
		photo: liz,
		name: 'User Name',
		role: 'User Role',
		company: 'Company Name',
		quote: `What matters to me is that these screens are in the right spot. It's the number one way I use Ring (computer and phone) …`,
		videoLabel: "User's story",
		videoUrl: 'Test Url',
		height: 450,
		width: 300,
	},
	{
		photo: liz,
		name: 'User Name',
		role: 'User Role',
		company: 'Company Name',
		quote: `What matters to me is that these screens are in the right spot. It's the number one way I use Ring (computer and phone) …`,
		videoLabel: "User's story",
		videoUrl: 'Test Url',
		height: 450,
		width: 300,
	},
	{
		photo: liz,
		name: 'User Name',
		role: 'User Role',
		company: 'Company Name',
		quote: `What matters to me is that these screens are in the right spot. It's the number one way I use Ring (computer and phone) …`,
		videoLabel: "User's story",
		videoUrl: 'Test Url',
		height: 450,
		width: 300,
	},
];
